// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TonVinhHienMau.Data;

namespace TonVinhHienMau.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220424013526_DonViDB")]
    partial class DonViDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TonVinhHienMau.Models.DonVi", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonVis");
                });

            modelBuilder.Entity("TonVinhHienMau.Models.NguoiHienMau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamSinh")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_10")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_100")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_15")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_20")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_30")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_40")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_5")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_50")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_60")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_70")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_80")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_90")
                        .HasColumnType("int");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_100")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_60")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_70")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_80")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_90")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("NguoiHienMau");
                });

            modelBuilder.Entity("TonVinhHienMau.Models.NguoiHienMau", b =>
                {
                    b.HasOne("TonVinhHienMau.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");
                });
#pragma warning restore 612, 618
        }
    }
}
